version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: sudo apt-get install -y git
      - run: |
          wget https://download.checkmarx.com/9.3.0GA/Plugins/CxConsolePlugin-1.1.5.zip
          mkdir CxConsolePlugin
          unzip CxConsolePlugin-1.1.5.zip -d CxConsolePlugin
          cd CxConsolePlugin
          chmod +x runCxConsole.sh
          pwd
          ./runCxConsole.sh Scan -CxServer https://lionx.checkmarx.net/ -TrustedCertificates -CxUser ars -CxPassword Teste@123 -LocationType "folder" -Projectname "/CxServer/JavaWebGoat_Default" -LocationPath "/home/circleci/project"  -Comment "Build Id : $CI_PIPELINE_ID" -Preset "Checkmarx Default" -ForceScan
workflows:
  build_scan: 
    jobs:
      - build-and-test

